name: pneumonia-detection
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pillow
  - scikit-learn
  - tqdm
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8